---

# Include variables and define needed variables.

- name: MONIT | Create directories
  block:
    - name: create includes folder
      file:
        path: "{{ monit_includes }}"
        state: directory
        mode: 0600
    - name: create id folder
      file:
        path: "{{ monit_lib_dir }}"
        state: directory
        mode: 0600
        owner: "{{ monit_user }}"
        group: "{{ monit_group }}"
    - name: MONIT | Create log directory
      file:
        path: "{{ monit_log_dir }}"
        state: directory
        owner: "{{ monit_user }}"
        group: "{{ monit_group }}"
    - name: MONIT | Create conf directories
      file:
        path: "{{ monit_conf_dir }}/{{ item }}/"
        state: directory
        owner: "{{ monit_user }}"
        group: "{{ monit_group }}"
        recurse: yes
      with_items:
        - conf.d
        - monitrc.d
  tags: monit_config


- name: MONIT | Config files
  block:
    - name: config - Setup monitrc
      template:
        src: monitrc.j2
        dest:  "{{monitrc_conf}}"
        owner: root
        group: root
        mode: 0700
      notify: restart monit

    - name: config - Setup webinterface
      template:
        src: webinterface.j2
        dest: "{{ monit_includes }}/webinterface"
        owner: root
        group: root
        mode: 0644
      notify: restart monit

    - name: config - Setup mail alerts
      template:
        src: mail.j2
        dest: "{{ monit_includes }}/mail"
        owner: root
        group: root
        mode: 0644
      notify: restart monit
      when: monit_mail_enabled
  tags: monit_config


- name: Create logrotate entry for monit.log
  template:
    src: logrotate_monit.j2
    dest: "/etc/logrotate.d/monit"
    owner: root
    group: root
    mode: 0644
  become: true
  when: ansible_os_family == "Debian"

- name: Put up Slack integration file if required
  template:
    src: slack.rb.j2
    dest: "/etc/monit/slack.rb"
    owner: root
    group: root
    mode: 0744
  become: true