---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags: monit_install

- include: install.yml
  tags: monit_install

- include: config.yml
  tags: monit_config

- include: monitors.yml
  tags: monit_monitors

- include: service.yml
  tags: monit_service


# - name: ensure monit starts on a fresh reboot
#   service: name=monit state=started enabled=yes

