---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags: monit_pkg

- include: config.yml
  tags: monit_config

- include: monitors.yml
  tags: monit_monitors

- name: Include OS-specific tasks.
  include: debian/logs.yml
  tags: monit_pkg
  when: ansible_os_family == "Debian"