---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags: monit_pkg

- include: config.yml
  tags: monit_config

- include: monitors.yml
  tags: monit_monitors

