---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags: always

- import_tasks: install.yml
  tags: monit_install

- import_tasks: config.yml
  tags: monit_config

- import_tasks: monitors.yml
  tags: monit_monitors

- import_tasks: service.yml
  tags: monit_service


# - name: ensure monit starts on a fresh reboot
#   service: name=monit state=started enabled=yes

