---
- name: Enable Backports repository (Debian).
  ansible.builtin.deb822_repository:
    name: "{{ ansible_facts['distribution_release'] }}-backports"
    types: deb
    uris: "http://ftp.debian.org/debian"
    suites: "{{ ansible_facts['distribution_release'] }}-backports"
    components: main
    state: present
  when: ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == '10'

- name: pkg - Install package
  apt:
    name: monit
    update_cache: true
    cache_valid_time: 3600
    state: present
  tags: monit_pkg
